services:
  shortener:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: shortener
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_HOST: shortener-postgres
    volumes:
      - ./out/logs:/app/out/logs
    ports:
      - "3000:3000"
    depends_on:
      shortener-postgres:
        condition: service_healthy

  shortener-postgres:
    container_name: shortener-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
