# --- build stage
FROM golang:1.25-alpine AS builder
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /app/server ./cmd/server

# --- run stage
FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/server .

EXPOSE 3000
CMD ["./server"]
